global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # SISClubes Backend - Production
  - job_name: 'sisclubes-backend'
    scheme: https
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets: ['sisclubes-backend-production.up.railway.app']
        labels:
          project: 'sisclubes'
          env: 'production'
    basic_auth:
      username: 'prometheus'
      password: 'SDI@dificil#8368'

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter.railway.internal:9187']

  # ? TODO: add your services here
  # - job_name: 'sdi-vistorias'
  #   scheme: https
  #   metrics_path: /metrics
  #   scrape_interval: 30s
  #   static_configs:
  #     - targets: ['sdi-vistorias-production.up.railway.app']
  #       labels:
  #         project: 'sdi-vistorias'
  #         env: 'production'
  #   basic_auth:
  #     username: 'prometheus'
  #     password: 'SENHA_DO_VISTORIAS'
